# See: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
name: build-devcontainers

on:
  workflow_dispatch
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
             ghcr.io/IITJ-RCAI/devcontainers-base
      -
      # https://github.com/docker/build-push-action/issues/252#issuecomment-879193129
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "https://github.com/docker/buildx.git#67bd6f4dc82a9cd96f34133dab3f6f7af803bb14"
          driver-opts: image=moby/buildkit:master
          buildkitd-flags: --debug
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
